name: Test macOS runners

on:
  push:

jobs:
  openssl:
    runs-on: macos-14 # beta but m1 arm64 arch
    steps:
    - name: Get env
      run: env
    - name: Default OpenSSL version
      run: openssl version
    - name: OpenSSl installed version(s)
      run: brew list | grep openssl
    - name: OpenSSL dirs
      run: |
        ls -la /opt/homebrew/etc/openssl\@1.1/
        ls -la /opt/homebrew/etc/openssl\@3/
        ls -la /opt/homebrew/etc/ca-certificates/
